import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import worker,{verifyStripe} from '../src/worker.mjs';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('schema.sql','utf8'));const DB={prepare(sql){return {bind(...args){const s=db.prepare(sql);return {first:async()=>s.get(...args)||null,run:async()=>s.run(...args)};}};}};let calls=0;return {db,env:{DB,QUOTA_SALT:'test-only-salt',DAILY_TRANSLATION_CAP:'200',AI:{run:async()=>{calls++;return {translated_text:'Hola'};}}},calls:()=>calls};}
const origin='https://example.com';
function req(path,data,headers={}){return new Request(origin+path,{method:data===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...headers},body:data===undefined?undefined:JSON.stringify(data)});}
test('CSRF fails before translation; public pages have browser protections',async()=>{const {env,calls}=setup();assert.equal((await worker.fetch(req('/api/translate',{text:'Hi',source:'en',target:'es'},{Origin:'https://attacker.test'}),env)).status,403);assert.equal(calls(),0);const r=await worker.fetch(req('/'),env);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal((await worker.fetch(req('/missing'),env)).status,404);});
test('translation enforces input, rate limits and global fuse',async()=>{const {env,calls}=setup();assert.equal((await worker.fetch(req('/api/translate',{text:'x'.repeat(501),source:'en',target:'es'}),env)).status,400);env.DAILY_TRANSLATION_CAP='1';const b={text:'Hi',source:'en',target:'es'};assert.equal((await worker.fetch(req('/api/translate',b),env)).status,200);assert.equal((await worker.fetch(req('/api/translate',b),env)).status,429);assert.equal(calls(),1);});
test('account keys hashed, cookies secure, restoration and logout work',async()=>{const {env,db}=setup();const r=await worker.fetch(req('/api/accounts',{}),env);assert.equal(r.status,201);const {recoveryKey}=await r.json();assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.notEqual(db.prepare('select recovery_hash from accounts').get().recovery_hash,recoveryKey.slice(3));const login=await worker.fetch(req('/api/login',{key:recoveryKey}),env);assert.equal(login.status,200);const Cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await (await worker.fetch(req('/api/account',undefined,{Cookie}),env)).json()).signedIn,true);await worker.fetch(req('/api/logout',{}, {Cookie}),env);assert.equal((await (await worker.fetch(req('/api/account',undefined,{Cookie}),env)).json()).signedIn,false);});
test('billing fails closed and forged webhook is rejected',async()=>{const {env}=setup();assert.equal((await worker.fetch(req('/api/checkout',{}),env)).status,503);assert.equal((await worker.fetch(req('/api/webhook',{type:'customer.subscription.updated'}),env)).status,400);assert.equal((await worker.fetch(req('/api/portal',{}),env)).status,401);});
test('Stripe signature requires untampered body and fresh timestamp',async()=>{const raw='{"hello":true}',t=123456,secret='test_secret';const sig=createHmac('sha256',secret).update(`${t}.${raw}`).digest('hex'),header=`t=${t},v1=${sig}`;assert.equal(await verifyStripe(raw,header,secret,t),true);assert.equal(await verifyStripe(raw+' ',header,secret,t),false);assert.equal(await verifyStripe(raw,header,secret,t+301),false);});
